# Game board settings
BOARD_SIZE = (10, 10)
MAX_MOVES = 1500
HISTORY_SIZE = 6
# Neural network training parameters
LEARNING_RATE = 0.001
BATCH_SIZE = 16
EPOCHS = 50
HIDDEN_LAYER_SIZE = 256
# Parameters for Genroot Games
NUM_GAMES = 10000
# Parameters for MCTS and PUCT
MCTS_SIMULATIONS = 700
PUCT_SIMULATIONS = 700
EXPLORATION_WEIGHT = 2
